<a href="https://colab.research.google.com/github/EdwSanA/DPro_Tareas/blob/main/Aplicacion_productos_matriciales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Producto matriz**
Considere las siguientes matrices A y B.

A=[−1234−5678−9],B=[02102−829−1]

**[Problema 1] El producto de matriz se calcula manualmente**

Resuelve el producto matricial de A y B a mano.

Explique también el proceso de cálculo utilizando el texto de rebaja.

Producto de matrices:

C = A × B

C[1,1] = (-1)(0) + (2)(0) + (3)(2)  = 6  
C[1,2] = (-1)(2) + (2)(2) + (3)(9)  = 29  
C[1,3] = (-1)(1) + (2)(-8) + (3)(-1) = -20  

C[2,1] = (4)(0) + (-5)(0) + (6)(2)  = 12  
C[2,2] = (4)(2) + (-5)(2) + (6)(9)  = 52  
C[2,3] = (4)(1) + (-5)(-8) + (6)(-1) = 38  

C[3,1] = (7)(0) + (8)(0) + (-9)(2)  = -18  
C[3,2] = (7)(2) + (8)(2) + (-9)(9)  = -51  
C[3,3] = (7)(1) + (8)(-8) + (-9)(-1) = -48

### Producto de matrices \(A*B)

El producto \(C = A B\) se calcula multiplicando cada fila de \(A\) por cada
columna de \(B\).  
El resultado es:

\[
A B =
\begin{bmatrix}
6  & 29 & -20 \\
12 & 52 &  38 \\
-18& -51& -48
\end{bmatrix}.
\]


**[Problema 2] Cálculo por función NumPy**

Este producto matricial de NumPy np.matmul () O np.dot () O @ @ Puede calcular fácilmente utilizando el operador.

Úselos para calcular el producto matricial.

numpy.matmul - Manual de NumPy v1.16

numpy.dot - Manual de NumPy v1.16

《Tres tipos de diferencia》

np.matmul () Cuando np.dot () Se comporta de manera diferente en matrices 3D o superiores. @ @ El operador es np.matmul () Funciona igual que.

En la matriz de multiplicación de una matriz bidimensional como esta vez np.matmul () O @ @ Los operadores son recomendados oficialmente. Lo siguiente es np.dot () Es una cita de la explicación.

Si tanto a como b son matrices 2-D, es una multiplicación matricial, pero se prefiere usar matmul o a @ b.

In [2]:
import numpy as np

# Definir las matrices A y B
A = np.array([[-1,  2,  3],
              [ 4, -5,  6],
              [ 7,  8, -9]])

B = np.array([[ 0,  2,  1],
              [ 0,  2, -8],
              [ 2,  9, -1]])

# 1) Usando np.matmul
C1 = np.matmul(A, B)

# 2) Usando el operador @ (equivale a np.matmul)
C2 = A @ B

# 3) Usando np.dot (para 2-D también es multiplicación de matrices)
C3 = np.dot(A, B)

print("Resultado con np.matmul:\n", C1)
print("\nResultado con operador @:\n", C2)
print("\nResultado con np.dot:\n", C3)


Resultado con np.matmul:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Resultado con operador @:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Resultado con np.dot:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**[Problema 3] Implementación del cálculo de cierto elemento**

Al hacer el cálculo manual, creo que presté atención a la fila 0 de la matriz A y la columna 0 de la matriz B, y realicé el siguiente cálculo.

Multiplique el elemento (0,0) $ a_ {0, 0} $ de la matriz A con el elemento (0,0) $ b_ {0, 0} $ de la matriz B
Multiplique el elemento (0,1) $ a_ {0, 1} $ de la matriz A con el elemento (1,0) $ b_ {1, 0} $ de la matriz B
Multiplique el elemento (0,2) $ a_ {0, 2} $ de la matriz A con el elemento (2,0) $ b_ {2, 0} $ de la matriz B
Suma todos esos valores.
Expresado como una fórmula

2∑K=0a0,KBK,0∑K=02a0,KBK,0

es.

Este calculo np.matmul () O np.dot () O @ @ Escriba el código para hacerlo sin usar operadores.

In [3]:
import numpy as np

A = np.array([[-1, 2,  3],
              [ 4,-5,  6],
              [ 7, 8, -9]])

B = np.array([[ 0, 2,  1],
              [ 0, 2, -8],
              [ 2, 9, -1]])

# Calcular manualmente el elemento (0,0) de A·B
c00 = 0
for k in range(A.shape[1]):           # recorre las 3 columnas de A (= 3 filas de B)
    c00 += A[0, k] * B[k, 0]

print("Elemento (0,0) de A·B =", c00)


Elemento (0,0) de A·B = 6


**[Problema 4] Crear una función que realice la multiplicación de matrices**

Extienda el código en el problema 3 para completar la implementación scratch del producto matriz. Debe ser una función que tome las matrices A y B como argumentos y devuelva el producto matricial.

Al calcular el producto matricial, repetirá el cálculo en el problema 3 para diferentes filas y columnas.

Cada elemento $ c_ {i, j} $ de la matriz C del resultado calculado $ 3 \ times 3 $ se expresa de la siguiente manera.

ci,j=2∑K=0ai,KBK,jci,j=∑K=02ai,KBK,j

Al usar la instrucción for y mover el índice ndarray, se puede calcular un total de 9 elementos. Puede aumentar el índice $ i $ o $ j $ en 1 para pasar a la siguiente fila o columna.

In [5]:
import numpy as np

def matrix_multiply(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """
    Calcula manualmente el producto matricial C = A × B
    sin usar np.matmul, np.dot ni el operador @.

    Parámetros
    ----------
    A : ndarray (m x n)
    B : ndarray (n x p)

    Retorna
    -------
    C : ndarray (m x p)
    """
    # Verificar compatibilidad de dimensiones
    if A.shape[1] != B.shape[0]:
        raise ValueError("Las dimensiones de A y B no permiten multiplicación")

    m, n = A.shape
    n2, p = B.shape
    C = np.zeros((m, p), dtype=A.dtype)

    # Triple bucle: fila de A, columna de B, suma de productos
    for i in range(m):          # recorre filas de A
        for j in range(p):      # recorre columnas de B
            s = 0
            for k in range(n):  # recorre columnas de A (= filas de B)
                s += A[i, k] * B[k, j]
            C[i, j] = s
    return C
A = np.array([[-1, 2,  3],
              [ 4,-5,  6],
              [ 7, 8, -9]])

B = np.array([[ 0, 2,  1],
              [ 0, 2, -8],
              [ 2, 9, -1]])

C = matrix_multiply(A, B)
print(C)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Ahora considere el siguiente ejemplo.

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])

e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

El producto matriz DE se define cuando el número de columnas de D es igual al número de filas de E, por lo que no se puede calcular en este ejemplo.

**[Problema 5] Juzgue la entrada cuyo cálculo no está definido**

Dependiendo del método de implementación, la función creada en el problema 4 puede funcionar incluso si se ingresa esta matriz D y E. En este caso, se realizarán cálculos incorrectos. Además, incluso si se produce un error en el medio, se muestra directamente un mensaje que es difícil de entender por qué ocurrió el error. Esto se evita mediante una declaración if, etc., y hay un problema en el formulario de entrada. impresión() Agregue el código para mostrar usando.

In [9]:
import numpy as np

def matrix_multiply(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """
    Producto matricial C = A × B hecho a mano.
    Si las dimensiones son incompatibles, muestra un
    mensaje claro y no intenta el cálculo.
    """
    # Comprobación de dimensiones
    if A.shape[1] != B.shape[0]:
        print("Error: el número de columnas de A "
              f"({A.shape[1]}) no coincide con el número de filas de B ({B.shape[0]}).")
        print("El producto A × B no está definido.")
        return None  # o podrías raise ValueError con un mensaje claro

    m, n = A.shape
    _, p = B.shape
    C = np.zeros((m, p), dtype=A.dtype)

    for i in range(m):
        for j in range(p):
            s = 0
            for k in range(n):
                s += A[i, k] * B[k, j]
            C[i, j] = s
    return C

In [10]:
d_ndarray = np.array([[-1, 2, 3],
                      [ 4,-5, 6]])
e_ndarray = np.array([[-9, 8, 7],
                      [ 6,-5, 4]])

result = matrix_multiply(d_ndarray, e_ndarray)
print("Resultado:", result)


Error: el número de columnas de A (3) no coincide con el número de filas de B (2).
El producto A × B no está definido.
Resultado: None


**[Problema 6] Transposición**

La transposición de una matriz le permite calcular el producto de la matriz.

np.transpose () O .T Transponer usando el atributo y calcular el producto matricial.

numpy.transpose - Manual de NumPy v1.16

numpy.ndarray.T - NumPy v1.16 Manual

In [15]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# Transposición de la matriz D para poder multiplicarla por E
d_transposed = d_ndarray.T

print("Matriz D original:\n", d_ndarray)
print("\nMatriz D transpuesta:\n", d_transposed)

# La multiplicación de D.T por E es posible
# (Filas de D.T = 3, Columnas de E = 2)
# Las dimensiones son (3x2) * (2x3), lo que produce una matriz (3x3)
product_de_transposed = d_transposed @ e_ndarray
print("\nProducto de D.T @ E:\n", product_de_transposed)

Matriz D original:
 [[-1  2  3]
 [ 4 -5  6]]

Matriz D transpuesta:
 [[-1  4]
 [ 2 -5]
 [ 3  6]]

Producto de D.T @ E:
 [[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
